services:
  - type: web
    name: nyasha-tutor
    runtime: node
    repo: https://github.com/MathiasChekanyanza/nyasha-tutor
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NYASHA_PORT
        value: 10000
      - key: AI_BOS_URL
        value: null
      - key: DEEPSEEK_API_KEY
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
